Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::group(['middleware' => 'auth:dcms'], function () {
            //ARTICLES
            Route::group(['prefix' => 'articles', 'as' => 'articles.'], function () {
                Route::get('{id}/copy', ['as' => 'copy', 'uses' => 'ArticleController@copy']);

                //CATEGORIES
                Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
                    Route::get('{id}/copy', ['as' => '{id}.copy', 'uses' => 'CategoryController@copy']);
                    Route::any('api/table', ['as' => 'api.table', 'uses' => 'CategoryController@getDatatable']);
                });
                Route::resource('categories', 'CategoryController');

                //API
                Route::group(['prefix' => 'api', 'as' => 'api.'], function () {
                    Route::any('table', ['as' => 'table', 'uses' => 'ArticleController@getDatatable']);
                    Route::any('products/table/{article_id?}', ['as' => 'products.table', 'uses' => 'ArticleController@getProductsDatatable']);
                    Route::any('relativearticles/table/{article_id?}', ['as' => 'relativearticles.table', 'uses' => 'ArticleController@getRelativeArticlesDatatable']);
                    Route::any('relation/table/{product_id?}', ['as' => 'relation.table', 'uses' => 'ArticleController@getRelationDatatable']);
                    Route::any('plants/table/{article_id?}', ['as' => 'plants.table', 'uses' => 'ArticleController@getPlantsDatatable']);
                    Route::any('faqrow', ['as' => 'faqrow', 'uses' => 'ArticleController@getFaqrow']);
                });
            });
            Route::resource('articles', 'ArticleController');
        });
    });
});

Models/Article.php
<?php
namespace Dcms\Dcmsarticles\Models;

use Dcms\Core\Models\EloquentDefaults;

class Article extends EloquentDefaults
{
    protected $connection = 'project';

    public function detail()
    {
        return $this->hasMany('Dcms\Dcmsarticles\Models\Detail', 'article_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo("Dcms\Dcmsarticles\Models\Category", 'article_category_id', 'id');
        //return $this->hasOne("Category");
    }

    public function productinformation()
    {
        return $this->belongsToMany('Dcms\Dcmsarticles\Models\Information', 'articles_to_products_information_group', 'article_id', 'information_id')->withTimestamps();
    }

    public function article()
    {
        return $this->belongsToMany('Dcms\Dcmsarticles\Models\Article', 'articles_to_articles', 'article_id', 'taggedarticle_id')->withTimestamps();
    }

    public function plants()
    {
        return $this->belongsToMany('Dcms\Plants\Models\Plant', 'article_to_plant', 'article_id', 'plant_id')->withTimestamps();
    }
}

Http/Controllers/ArticleController.php
<?php
namespace Dcms\Dcmsarticles\Http\Controllers;

use DB;
use Auth;
use Form;
use Mail;
use View;
use Input;
use Session;
use DateTime;
use Redirect;
use Validator;
use DataTables;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Dcms\Plants\Models\Plant;
use App\Jobs\ProcessNewArticle;
use Dcms\Dcmsarticles\Models\Faq;
use Dcms\Products\Models\Product;
use App\Jobs\ProcessUpdateArticle;
use App\Http\Controllers\Controller;
use Dcms\Dcmsarticles\Models\Detail;
use Dcms\Dcmsarticles\Models\Article;
use Dcms\Dcmsarticles\Models\Category;
use Illuminate\Support\Facades\Schema;

class ArticleController extends Controller
{
    public $article_language_Columnnames = [];
    public $article_Columnnames = [];
    public $article_ColumnNamesDefaults = [];
    public $information_ColumnNamesDefaults = [];

    public $articlelanguageFormTemplate = '';
    public $articleFormTemplate = '';

    public $extendgeneralTemplate = '';

    public function __construct()
    {
        $this->middleware('permission:articles-browse')->only('index');
        $this->middleware('permission:articles-add')->only(['create', 'store']);
        $this->middleware('permission:articles-edit')->only(['edit', 'update']);
        $this->middleware('permission:articles-delete')->only('destroy');

        //note startdate and enddate are defaults, since these are always there, and have a specific value (not simple text, or bool)
        $this->article_Columnnames = [
            'thumbnail' => 'thumbnail',
            'enabletime' => 'enabletime',
            'birthdaycycle' => 'birthdaycycle',
            'online' => 'online',
            'newarticle' => 'newarticle',
            'calendar' => 'calendar',
        ];

        $this->article_language_Columnnames = [
            'article_category_id' => 'category_id',
            'highpriority' => 'highpriority',
            'megamenu' => 'megamenu',
            'largevisual' => 'largevisual',
            'title' => 'title',
            'description' => 'description',
            'meta_description' => 'meta_description',
            'body' => 'body',
            'slug' => 'title',
            'path' => 'title',
            'url' => 'url',
            'log' => 'log',
            'keywords' => 'keywords',
            'script' => 'script',
            'thumbnail_alt' => 'thumbnail_alt',
        ];

        $this->article_ColumnNamesDefaults = [
            'enabletime' => '0',
            'birthdaycycle' => '0',
            'enablemorebtn' => '0',
            'online' => '0',
            'actionarticle' => '0',
            'thumbnailindetail' => '0',
            'newarticle' => '0',
            'calendar' => '0'];

        $this->information_ColumnNamesDefaults = [
            'highpriority' => '0', 
            'megamenu' => '0', 
            'largevisual' => '0', ];

        $this->articlelanguageFormTemplate = null;
        $this->articleFormTemplate = null;
    }

    public static function getArticlesDetailByLanguage($language_id = null)
    {
        return Detail::where('language_id', '=', $language_id)->lists('title', 'id');
    }

    public static function getDropdownArticlesByLanguage($language_id = null)
    {
        $dropdownvalues = ArticleController::getArticlesDetailByLanguage($language_id);

        return Form::select('article[' . $language_id . '][]', $dropdownvalues, [3, 4, 5, 6], ['id' => 'articles-' . $language_id, 'multiple' => 'multiple']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $sectors = DB::connection('project')
            ->table('vwpages_language')
            ->select(
                'title',
                'language_id',
                'division'
            )
            ->where('depth', '=', '2')
            ->orderBy('title')
            ->get();

        // load the view
        return View::make('dcms::articles/index')->with('sectors', $sectors);
    }

    public function getDatatable()
    {
        $query = DB::connection('project')
            ->table('articles')
            ->select(
                'articles.id',
                'articles_language.title',
                'articles_language.highpriority',
                'articles_language.id as article_language_id',
                (DB::connection('project')->raw('Concat("<img src=\'/packages/Dcms/Core/images/flag-",lcase(country),".svg\' style=\'width:16px; height:auto;\'>") as country'))
            )
            ->join('articles_language', 'articles.id', '=', 'articles_language.article_id')
            ->leftJoin('languages', 'articles_language.language_id', '=', 'languages.id');

        if (intval(session('overrule_default_by_language_id')) > 0) {
            $query->where('articles_language.language_id', session('overrule_default_by_language_id'));
        }

        if (Session::has('pagefilter')) {
            $filter = Session::get('pagefilter');

            foreach ($filter as $column => $colvalues) {
                if ($column == 'language_id') {
                    foreach ($colvalues as $colvalue) {
                        $query->orWhere('articles_language.language_id', '=', $colvalue);
                    }
                }

                $query->where(function ($q) use ($column, $colvalues) {
                    if ($column == 'language_id') {
                        foreach ($colvalues as $colvalue) {
                            $q->orWhereRaw('articles.id IN (SELECT id FROM vwarticles_to_pages WHERE language_id = "' . $colvalue . '" )');
                        }
                    }
                    if ($column == 'division') {
                        foreach ($colvalues as $colvalue) {
                            $q->orWhereRaw('articles.id IN (SELECT id FROM vwarticles_to_pages WHERE division_url = "' . $colvalue . '" )');
                        }
                    }
                    if ($column == 'sector') {
                        foreach ($colvalues as $colvalue) {
                            if ($colvalue <> '0' && $colvalue <> '' && !is_null($colvalue)) {
                                $q->orWhereRaw('articles.id IN (SELECT id FROM vwarticles_to_pages WHERE sector_url = "' . $colvalue . '" )');
                            }
                        }
                    }
                });
            }
        }

        return Datatables::queryBuilder($query)
                        ->addColumn('edit', function ($model) {
                            return '<form method="POST" action="/admin/articles/' . $model->article_language_id . '" accept-charset="UTF-8" class="pull-right">
							<input name="_token" type="hidden" value="' . csrf_token() . '">
							<input name="_method" type="hidden" value="DELETE">
							<a class="btn btn-xs btn-default" href="/admin/articles/' . $model->id . '/edit"><i class="far fa-pencil"></i></a>
							<a class="btn btn-xs btn-default" href="/admin/articles/' . $model->article_language_id . '/copy"><i class="far fa-copy"></i></a>
							<button class="btn btn-xs btn-default" type="submit" value="Delete this article" onclick="if(!confirm(\'Are you sure to delete this item?\')){return false;};"><i class="far fa-trash-alt"></i></button>
						</form>';
                        })
                        ->rawColumns(['country', 'edit'])
                        ->make(true) ;
    }

    /**
     * get the data for DataTable JS plugin.
     *
     * @return Response
     */
    public function getProductsDatatable($article_id = 0)
    {
        $queryA = DB::connection('project')
        ->table('products_information as x')
        ->select(
            (
                DB::connection('project')->raw('
                case when (select count(*) from articles_to_products_information_group where articles_to_products_information_group.information_group_id = x.information_group_id and article_id = "' . $article_id . '") > 0 then 1 else 0 end as checked,
                catalogue,
                title,
                languages.country,
                information_group_id')
            )
        )
        ->leftJoin('languages', 'x.language_id', '=', 'languages.id')
        // ->whereRaw('x.id IN (SELECT product_information_id FROM products_to_products_information WHERE product_id IN ( SELECT id FROM products WHERE online = 1 ) )')
        ->whereNotNull('x.information_group_id')
        ->orderBy('checked', 'DESC');

        $queryB = clone $queryA;
        $queryB->whereRaw('case when (select count(*) from articles_to_products_information_group where articles_to_products_information_group.information_group_id = x.information_group_id and article_id = "' . $article_id . '") > 0 then 1 else 0 end = 1');

        if (intval(session('overrule_default_by_language_id')) > 0) {
            $queryA->where('x.language_id', session('overrule_default_by_language_id'));
        }

        return Datatables::queryBuilder($queryB->union($queryA)->orderBy('checked', 'desc'))
                ->addColumn('radio', function ($model) {
                    return '<input type="checkbox" name="information_group_id[]" value="' . $model->information_group_id . '" ' . ($model->checked == 1 ? 'checked="checked"' : '') . ' id="chkbox_' . $model->information_group_id . '" > ';
                })
                ->addColumn('language', function ($model) {
                    return '<img src="/packages/Dcms/Core/images/flag-' . strtolower($model->country) . '.svg" style="width:16px; height: auto;" alt="">';
                })
                ->rawColumns(['radio', 'language'])
                ->make(true);
    }

    public function getRelationDatatable($product_id = 0)
    {
        $information_group_id = 0;
        $ProductInformation = Product::with('information')->find($product_id);

resources/views/articles/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Articles</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-newspaper"></i> Articles</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('articles-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/articles/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>
                    <div class="panel filter up">
                        <div class="panel-heading">
                            <h3>Filter <i class="far fa-plus-square right"></i></h3>
                        </div>
                        <div class="panel-body" @if(Session::has('pagefilter')) style="display:block;" @endif>
                            <form method="GET" action="/admin/articles" accept-charset="UTF-8">

                                <?php
                                if (Request::has('resetfilters') && Request::get('resetfilters') == 'true') {
                                    Session::forget('pagefilter');
                                }
                                ?>

                                @if(Request::has('page') || Session::has('pagefilter'))
                                    @if(Request::has('page'))
                                        <?php
                                        Session::put('pagefilter', Request::get('page')); //put in a session so the Datatable request can accesss the variables
                                        ?>
                                    @endif
                                @endif

                                <h4>Country</h4>
                                <ul>
                                    <li style="display:inline;"><label for="be"><input class="changeLanguage" type="checkbox" name="page[language_id][1]" id="be" value="1"
                                                                                       @if(Session::has('pagefilter.language_id') && Session::has('pagefilter.language_id.1')) checked @endif >
                                            <img src="/packages/Dcms/Core/images/flag-be.svg" style="width:16px; height: auto;"></label></li>
                                    <li style="display:inline; margin-left:15px;"><label for="nl"><input class="changeLanguage" type="checkbox" name="page[language_id][3]"
                                                                                                         id="nl" value="3"
                                                                                                         @if(Session::has('pagefilter.language_id') && Session::has('pagefilter.language_id.3')) checked @endif>
                                            <img src="/packages/Dcms/Core/images/flag-nl.svg" style="width:16px; height: auto;"></label></li>
                                    <li style="display:inline; margin-left:15px;"><label for="fr"><input class="changeLanguage" type="checkbox" name="page[language_id][6]"
                                                                                                         id="fr" value="6"
                                                                                                         @if(Session::has('pagefilter.language_id') && Session::has('pagefilter.language_id.6')) checked @endif>
                                            <img src="/packages/Dcms/Core/images/flag-fr.svg" style="width:16px; height: auto;"></label></li>
                                    <li style="display:inline; margin-left:15px;"><label for="de"><input class="changeLanguage" type="checkbox" name="page[language_id][7]"
                                                                                                         id="de" value="7"
                                                                                                         @if(Session::has('pagefilter.language_id') && Session::has('pagefilter.language_id.7')) checked @endif>
                                            <img src="/packages/Dcms/Core/images/flag-de.svg" style="width:16px; height: auto;"></label></li>
                                </ul>
                                <hr>
                                <h4>Division</h4>
                                <ul>
                                    <li style="display:inline;"><label for="hobby"><input class="changeDivision" type="checkbox" name="page[division][hobby]" id="hobby"
                                                                                          value="hobby"
                                                                                          @if(Session::has('pagefilter.division') && Session::has('pagefilter.division.hobby')) checked @endif>
                                            Hobby</label></li>
                                    <li style="display:inline; margin-left:15px;"><label for="pro"><input class="changeDivision" type="checkbox" name="page[division][pro]"
                                                                                                          id="pro" value="pro"
                                                                                                          @if(Session::has('pagefilter.division') && Session::has('pagefilter.division.pro')) checked @endif>
                                            Professional</label></li>
                                </ul>
                                <hr>
                                <h4>Sector</h4>
                                <select class="form-control" name="page[sector][]">
                                    <option value="">-all-</option>
                                    <?php
                                    $allreadyprinted = [];
                                    ?>
                                    @foreach($sectors as $sector)
                                        <option class='sectordd sectorlanguage{{$sector->language_id}} sectordivision{{strtolower($sector->division)}}'
                                                value="{{$sector->title}}"
                                                @if(Session::has('pagefilter.sector') && Session::get('pagefilter.sector.0') == $sector->title ) selected @endif>{{$sector->title}}</option>
                                    @endforeach

                                </select>
                                <div class="btnbar btnbar-left" style="margin-top:15px;">
                                    {!! Form::button('Set Filter', array('class' => 'btn btn-primary', 'type'=>'submit')) !!}
                                    <a class="btn btn-default" href="{{url('admin/articles?resetfilters=true')}}">Reset Filter</a>
                                </div>
                            </form>
                        </div>
                    </div>

                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Country</th>
                            <th>Highpriority</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {

                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.articles.api.table') }}",
                                "columns": [
                                    {data: 'id', name: 'ID'},
                                    {data: 'title', name: 'articles_language.title'},
                                    {data: 'country', name: 'country', searchable: false},
                                    {data: 'highpriority', name: 'highpriority', searchable: false},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>
@stop

@section("script")
    <script type="text/javascript">

        languageFilter = "";
        divisionFilter = "";

        function filterLanguage() {
            $('.changeLanguage').each(function (index) {
                if ($(this)[0].checked == true) {
                    languageFilter = '.sectorlanguage' + $(this)[0].value;
                    $('.sectorlanguage' + $(this)[0].value + divisionFilter).show();
                } else {
                    $('.sectorlanguage' + $(this)[0].value).hide();
                }
            });
        }

        function filterDivision() {
            $('.changeDivision').each(function (index) {
                if ($(this)[0].checked == true) {
                    divisionFilter = '.sectordivision' + $(this)[0].value;
                    $(languageFilter + '.sectordivision' + $(this)[0].value).show();
                } else {
                    $('.sectordivision' + $(this)[0].value).hide();
                }
            });
        }

        $(document).ready(function () {
            $('.sectordd').hide();
            filterLanguage();
            filterDivision();

            $('.changeLanguage').change(function () {
                filterLanguage();
            })

            $('.changeDivision').change(function () {
                filterDivision();
            })

            //Filter toggle
            $('.filter .panel-heading').click(function () {
                $(this).closest('.panel').toggleClass('up');
            });

            $("#btn-reset").click(function () {
                var appendDiv = jQuery($(".condition:last")[0].outerHTML);
                $(".condition").remove();
                $("#filters").prepend(appendDiv.attr('id', '0'));
                $("#0").find('select').val('0');
                $("#0").find('input[type=text]').val('');
            });

            //Add condition
            $('.add-condition').click(function () {
                var id = $(".condition:last").attr('id');
                var appendDiv = jQuery($(".condition:last")[0].outerHTML);

                appendDiv.attr('id', ++id).insertAfter(".condition:last");

                $("#" + id).find('select').val('0');
                $("#" + id).find('input[type=text]').val('');

                return false;
            });

        });
    </script>
@stop